In [1]:
import dai
import pandas as pd

bsd = '2024-12-30'
sd = '2025-01-01'
ed = '2026-05-01'

df = dai.query('SELECT date, instrument, close/m_lag(close, 1) as factor FROM cn_stock_bar1d', filters={'date': [bsd, ed]}).df()
df = df[(df['date']>=sd) & (df['date']<=ed)]

index_df = dai.query(
    "SELECT date, member_code as instrument FROM cn_stock_index_component WHERE instrument = '000852.SH'",
    filters={"date": [sd, ed]},
).df()

df = pd.merge(df, index_df, how='right', on=['date', 'instrument'])
df

             date instrument    factor
0      2025-01-02  000012.SZ  0.973485
1      2025-01-02  000019.SZ  0.993912
2      2025-01-02  000025.SZ  0.987288
3      2025-01-02  000028.SZ  0.968205
4      2025-01-02  000029.SZ  0.983400
...           ...        ...       ...
319995 2026-01-07  688776.SH  1.057747
319996 2026-01-07  688779.SH  0.992491
319997 2026-01-07  688789.SH  0.996112
319998 2026-01-07  688798.SH  1.000000
319999 2026-01-07  688800.SH  1.014076

[320000 rows x 3 columns]

In [2]:
import os
import sys
path = '/home/aiuser/work/BigAlpha/eval'
if path not in sys.path:
    sys.path.append(path)

In [3]:
from dataprocess.datachecker import DataCheck
from dataprocess.dataprocess import DataProcess
DataCheck(sd, ed).validate(df)
DataProcess(sd, ed).validate(df)

[2026-05-27 16:59:49] [info     ] 通过：列名检查（必须且仅三列）
[2026-05-27 16:59:49] [info     ] 通过：instrument 格式检查
[2026-05-27 16:59:49] [info     ] 通过：factor 有限值检查（禁止 inf/-inf）
[2026-05-27 16:59:49] [info     ] 通过：时间范围检查
[2026-05-27 16:59:49] [info     ] 通过：交易日完整性检查
[2026-05-27 16:59:49] [info     ] 通过：唯一性检查
[2026-05-27 16:59:49] [info     ] 通过：股票池范围检查（中证1000历史成分）
[2026-05-27 16:59:49] [info     ] 通过：覆盖度检查（每交易日缺失率<=40%）
[2026-05-27 16:59:49] [info     ] inf 处理, 耗时: 0.0019 秒
[2026-05-27 16:59:50] [info     ] 去极值, 耗时: 0.0911 秒
[2026-05-27 16:59:50] [info     ] 标准化, 耗时: 0.0882 秒
[2026-05-27 17:00:07] [info     ] 风格剔除(取残差), 耗时: 17.0264 秒

             date instrument    factor
0      2025-01-02  000012.SZ  0.188119
1      2025-01-02  000019.SZ  0.491501
2      2025-01-02  000025.SZ -0.268453
3      2025-01-02  000028.SZ -0.618521
4      2025-01-02  000029.SZ -0.149667
...           ...        ...       ...
319995 2026-04-30  688776.SH  0.215749
319996 2026-04-30  688779.SH -1.554578
319997 2026-04-30  688789.SH -3.402149
319998 2026-04-30  688798.SH  0.115841
319999 2026-04-30  688800.SH  2.475192

[320000 rows x 3 columns]